### ISSUE TITLE
hosts template not found

### ISSUE THREAD

**Issue by rafabene** [Project31/ansible-kubernetes-openshift-pi3#1]
When running base task it fails at https://github.com/Project31/ansible-kubernetes-openshift-pi3/blob/master/roles/base/tasks/system.yml#L31

The error is: => input file not found at /home/pi/ansible-kubernetes-openshift-pi3/roles/base/templates/hosts or /home/pi/ansible-kubernetes-openshift-pi3/hosts

**Comment by rhuss** [comment]
Sorry, forgot `hosts` template because it "hosts" is entered in the toplevel .gitignore (for the ansible host config). 

Thanks for spotting this.
