### ISSUE TITLE
typo in header

### ISSUE THREAD

**Issue by vielmetti** [Project31/ansible-kubernetes-openshift-pi3#14]
Header of repo reads

> Experimental Ansible playbook for setting up Kubernetes on Rasperry Pi 3

which should be

> Experimental Ansible playbook for setting up Kubernetes on Raspberry Pi 3

also, would be good to tag the repo with some keywords for ease of location and further retrieval - I had partially lost this one from memory until another issue had been opened to bring it back to recall.

**Comment by rhuss** [comment]
Thanks for the heads up ! Update title and added some labels.
