### ISSUE TITLE
Task: "Check for an already generated token" requires local sudo without password

### ISSUE THREAD

**Issue by zorel** [Project31/ansible-kubernetes-openshift-pi3#16]
Hello.

I'm in the process to install kubernetes on my raspberry pi from my Linux box. On this box, my user uses sudo, but sudo is not configured to connect without password.

So, ansible's local actions fail:
```
TASK [kubernetes : Check for an already generated token]

fatal: [192.168.0.20 -> localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "sudo: a  password is required\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```

Enabling sudo without password on the ansible box make it work. 

This should be indicated in the readme (or I missed it).

**Comment by rhuss** [comment]
Thanks for the heads up. I probably have to find out how to run a `local_action` without `sudo` as sudo is not required here at all (its just to store some config and the token within the playbook dir)
