### ISSUE TITLE
v0.2.0 One or more undefined variables: 'dict object' has no attribute 'etcd'

### ISSUE THREAD

**Issue by Hades32** [Project31/ansible-kubernetes-openshift-pi3#3]
TASK: [etcd | Download Binaries] **********************************************
fatal: [163.172.142.208 -> 127.0.0.1] => One or more undefined variables: 'dict object' has no attribute 'etcd'

also (before me copying the file to the right position)
[h32@UbuntuMATE ansible-kubernetes-openshift-pi3]$ ansible-playbook -vvvv -i hosts kubernetes.yml
ERROR: file could not read: /data/h32/ansible-kubernetes-openshift-pi3/roles/includes/install_binaries.yml

It seems to me that the state is a little broken for the kubernetes (not openshift) setup...

BTW are you doing tests on Scaleway's ARM servers? I'm currently trying to get your scripts running there...

**Comment by Hades32** [comment]
$ ansible --version
ansible 1.9.2
  configured module search path = None

$ cat /etc/debian_version
jessie/sid

**Comment by Hades32** [comment]
oh.. I missed the (very small...) comment about Ansible _2_...

**Comment by rhuss** [comment]
I will add this more prominently, thanks !
