### ISSUE TITLE
Suggestion: Pin Kubernetes components (like Docker)

### ISSUE THREAD

**Issue by robertpeteuil** [Project31/ansible-kubernetes-openshift-pi3#41]
Hi @rhuss - congrats on keeping this repo updated and current!  I had helped out a bit about 6 months ago before you had added support with Hypriot 1.5.

**Comment by rhuss** [comment]
@robertpeteuil currently I'm fighting a bit with the latest Kubernetes versions 1.9 and 1.10. which raised several issues on the Pi, especially extensive CPU usage of the APIserver. Not sure whether this is related also to the lastest update of Hypriot itself, so I have to start playing again with various versions.

As soon as I found a "good" combination, pinning these versions is indeed a very good idea.
