### ISSUE TITLE
Getting an error running the kubernetes playbook

### ISSUE THREAD

**Issue by ahillman3** [Project31/ansible-kubernetes-openshift-pi3#5]
I get a fair way through the playbook when this error occurs:

```
TASK [kubernetes : Install kubelet service definition] *************************
fatal: [192.168.1.59]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'dns' is undefined"}

```

I see **dns.service_ip** in the kubelet.service, but don't see where that should already have been defined.
Any assistance would be appreciated.

**Comment by rhuss** [comment]
Ah, sorry, its a regression.

Will fix that over the weekend.

In the meantime, could you copy over https://github.com/Project31/ansible-kubernetes-openshift-pi3/blob/master/roles/skydns/defaults/main.yml#L13-L15 to https://github.com/Project31/ansible-kubernetes-openshift-pi3/blob/master/roles/kubernetes/defaults/main.yml ?

**Comment by ahillman3** [comment]
I'll try that tonight. Thanks.

**Comment by ahillman3** [comment]
That worked. Thanks.

**Comment by rhuss** [comment]
Cool, close it now.
